console.log(
    colors.bold.cyan("           *******************************************\n"),
    colors.bold.cyan("          **               ", colors.rainbow("WELCOME"),"               **\n"),
    colors.bold.cyan("          **                 ", colors.rainbow("TO"),"                  **\n"),
    colors.bold.cyan("          **                ", colors.rainbow("LIRI"),"                 **\n"),
    colors.bold.cyan("          *******************************************\n"),
    colors.bold.cyan("          *******************************************\n"),
    colors.bold.cyan("          **            ", colors.brightMagenta.bold.underline("  COMMANDS:  "),"            **\n"),
    colors.bold.cyan("          **                                       **\n"),
    colors.bold.cyan("          **   ", colors.yellow("concert-this <artist/band name>"),"   **\n"),
    colors.bold.cyan("          **   ", colors.yellow("spotify-this-song <song title>"),"    **\n"),
    colors.bold.cyan("          **   ", colors.yellow("movie-this <movie title>"),"          **\n"),
    colors.bold.cyan("          **   ", colors.yellow("do-what-it-says"),"                   **\n"),
    colors.bold.cyan("          *******************************************\n"),
);